# 02:17 - Overview of GitHub Actions
# 05:15 - Workflow syntax
# 18:11 - GitHub web editor & syntax validation
# 20:10 - Building the issue comments workflow
# 23:53 - Using a community action
# 26:08 - Using GitHub REST APIs in workflows

name: E2E Test Report
run-name: ${{ github. }} is learning GitHub Actions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 8 * * *" # workflow will run daily at 8:00 AM
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
