name: Playwright Tests
on:
  push:
    branches: main

  pull_request:
    branches: main 

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  checks: write
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: 14
    # - name: Install dependencies
    #   run: npm ci

    # - name: Start WordPress Env
    #   run: |
    #     npm run start:env 

    # - name: Activate theme:Storefront
    #   run: |
    #     npm run wp-env run tests-cli 'wp theme activate storefront' 

    # - name: Install Playwright Browsers
    #   run: npx playwright install chromium

    # - name: Run Playwright tests
    #   run: REPORT=api npx playwright test --project=api

    # - name: Run Playwright tests
    #   run: REPORT=test_b npx playwright test --project=test_b

    - name: Publish Test Report a
      uses: mikepenz/action-junit-report@v3.7.7
      if: always() 
      with:
        report_paths: 'playwright-report/junit-report/e2e-results.xml'
        include_passed: false,
        check_retries: true,
        detailed_summary: fasle,
        check_name: 'E2E Test Report'   # Check name to use when creating a check run.
        summary: 'E2E Test Summary Report (JUnit)_summary'  # Additional text to summary output
        # annotate_only: true,
        # annotate_notice: true,
        job_name: 'e2e2e2e2e2e2e2e_jobName'
        # job_summary: true,
        # test_files_prefix: 'ABC_'
        token: ${{ secrets.GITHUB_TOKEN }}

    
    # - name: Publish Test Report b
    #   uses: mikepenz/action-junit-report@v3
    #   if: always() 
    #   with:
    #     report_paths: 'playwright-report/test_b/junit-report/e2e-results.xml'
    #     include_passed: TRUE,
    #     check_retries: TRUE,
    #     detailed_summary: TRUE,
    #     check_name: 'E2E Test Report (JUnit)_test_b'
    #     summary: 'E2E Test Summary Report (JUnit)_summary'
    #     # annotate_only: true,
    #     # annotate_notice: true,
    #     # job_name: 'e2e2e2e2e2e2e2e_jobName'

    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: test-results
    #     retention-days: 30
