name: Playwright Tests
on:
  push:
    branches: main

  pull_request:
    branches: main 

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: 14
    # - name: Install dependencies
    #   run: npm ci

    # - name: Start WordPress Env
    #   run: |
    #     npm run start:env 

    # - name: Activate theme:Storefront
    #   run: |
    #     npm run wp-env run tests-cli 'wp theme activate storefront' 

    # - name: Install Playwright Browsers
    #   run: npx playwright install chromium

    # - name: Run Playwright tests
    #   run: REPORT=api npx playwright test --project=api

    # - name: Run Playwright tests
    #   run: REPORT=test_b npx playwright test --project=test_b

    # - name: Publish Test Report a
    #   uses: mikepenz/action-junit-report@v3.7.7
    #   id: test-res
    #   if: always() 
    #   with:
    #     report_paths: 'playwright-report/junit-report/e2e-results.xml'
    #     include_passed: false,
    #     check_retries: true,
    #     detailed_summary: fasle,
    #     check_name: 'E2E Test Report'   # Check name to use when creating a check run.
    #     summary: 'E2E Test Summary Report (JUnit)_summary'  # Additional text to summary output
    #     # annotate_only: true,
    #     annotate_notice: true,
    #     job_name: 'e2e2e2e2e2e2e2e_jobName'
    #     job_summary: true,
    #     # test_files_prefix: 'ABC_'
    #     token: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Generate list using Markdown
    #   run: |
    #       echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
    #       echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
    #       echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
    #       echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
    #       echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

    - name: Prepare test summary
      id: prepare-test-summary
      uses: actions/github-script@v6.4.1
      with:
          result-encoding: string
          script: |
              const script = require("./testSummary.ts" )
              await script({github, context, core})

    - name: Find PR comment by github-actions[bot]
      uses: peter-evans/find-comment@034abe94d3191f9c89d870519735beae326f2bdb
      id: find-comment
      with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test Results Summary
          
    - name: Create or update PR comment
      uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d
      with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.prepare-test-summary.outputs.result }}
          edit-mode: replace


    # - name: Publish Test Report b
    #   uses: mikepenz/action-junit-report@v3
    #   if: always() 
    #   with:
    #     report_paths: 'playwright-report/test_b/junit-report/e2e-results.xml'
    #     include_passed: TRUE,
    #     check_retries: TRUE,
    #     detailed_summary: TRUE,
    #     check_name: 'E2E Test Report (JUnit)_test_b'
    #     summary: 'E2E Test Summary Report (JUnit)_summary'
    #     # annotate_only: true,
    #     # annotate_notice: true,
    #     # job_name: 'e2e2e2e2e2e2e2e_jobName'

    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: test-results
    #     retention-days: 30
