name: Playwright Tests
# run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  FORCE_COLOR: 1
  GMAP: ${{secrets.GMAP}}
  ABC: ${{secrets.GGG}}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
      - name: Get System Information
        run: |
          echo "CPU Information:"
          lscpu

          echo "Memory Information:"
          lsmem
          free -h

          echo "Disk Information:"
          df -h

          echo "OS Information:"
          uname -a
          cat /etc/os-release

          echo "Detailed CPU Info:"
          cat /proc/cpuinfo

          echo "Detailed Memory Info:"
          cat /proc/meminfo

      - name: View Environment Variables
        run: |
          echo "GitHub Repository: ${{ secrets.GMAP }}"
          echo "GitHub Repository: $GMAP"
          echo "GitHub Repository: $GGG"
          echo env

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci

      - name: Start WordPress Env
        run: |
          npm run start:env

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run Playwright tests
        id: test
        run: npx playwright test

      # # - name: Publish Test Report
      # #   uses: mikepenz/action-junit-report@v3
      # #   if: always()
      # #   with:
      # #     report_paths: "junit-report/e2e-results.xml"
      # #     job_summary: false
      # #     annotate_only: true,
      # #     # include_passed: true,
      # #     # check_retries: true,
      # #     # detailed_summary: true,
      # #     check_name: 'E2E Test Report'
      # #     summary: 'E2E Test Summary Report (JUnit)_summary'
      # # annotate_notice: true,
      # # job_name: 'e2e2e2e2e2e2e2e_jobName'

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: test-results
      #     retention-days: 30
