name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci

    - name: Start WordPress Env
      run: |
        npm run start:env 

    - name: Install Playwright Browsers
      run: npx playwright install chromium

    - name: Run Playwright tests
      run: npx playwright test

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() 
      with:
        report_paths: "junit-report/e2e-results.xml"
        # include_passed: TRUE,
        # check_retries: TRUE,
        # detailed_summary: true,
        check_name: 'E2E Test Report (JUnit)_check_nem'
        summary: 'E2E Test Summary Report (JUnit)_summary'
        # annotate_only: true,
        annotate_notice: true,
        job_name: 'e2e2e2e2e2e2e2e_jobName'

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: test-results
        retention-days: 30
